# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[
        'connectors.sqlite_connector',
        'connectors.postgres_connector',
        'connectors.mysql_connector',
        'connectors.mongodb_connector',
        'connectors.redis_connector',
        'connectors.cassandra_connector',
        'connectors.safebridge_client',
        'features.ai_helper',
        'features.cerebro_sql',
        'features.asistente_voz',
        'features.panel_rendimiento',
        'features.programador_tareas',
        'features.usuarios',
        'features.comparador',
        'features.ux_mejoras',
        'features.bookmarks',
        'features.erd_generator',
        'utilidades.detector',
        'extraccion.conector',
        'transformacion.mapeador',
        'carga.cargador',
        'speech_recognition',
        'pyttsx3.drivers',
        'pyttsx3.drivers.sapi5',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='NexusDB',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
